const projects = [
  {
    _id: "1",
    name: "Project 1",
    image: "/images/project1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Project",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    likes: 0,
  },
  {
    _id: "2",
    name: "Project 2",
    image: "/images/project2.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    category: "Project",
    likes: 0,
  },
  {
    _id: "3",
    name: "Project 3",
    image: "/images/project3.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    category: "Project",
    likes: 0,
  },
  {
    _id: "4",
    name: "Project 4",
    image: "/images/project4.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    category: "Project",
    likes: 0,
  },
  {
    _id: "5",
    name: "Project 5",
    image: "/images/project5.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    category: "Project",
    likes: 0,
  },
  {
    _id: "6",
    name: "Project 1",
    image: "/images/project1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Project",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aut commodi, fugit velit nemo recusandae voluptas molestias quo sint esse rem ad temporibus fugiat, at excepturi a corporis odit totam.",
    likes: 0,
  },
];

export default projects;
